package com.coins.mapper.rbac;

import com.coins.entity.rbac.Admin;
import java.util.List;

public interface AdminMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admins
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admins
	 * @mbg.generated
	 */
	int insert(Admin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admins
	 * @mbg.generated
	 */
	Admin selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admins
	 * @mbg.generated
	 */
	List<Admin> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admins
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Admin record);
}